name: invia_case_study
description: "Invia Case Study"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  get_it: ^8.0.2
  injectable: ^2.5.0
  dartz: ^0.10.1
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_route: ^7.8.4
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  connectivity_plus: ^6.1.0
  dio: ^5.7.0
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1
  auto_route_generator: ^7.3.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/img/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
