name: invia_case_study
description: "Invia Case Study"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  get_it: ^8.0.2
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.2

flutter:
  generate: true
  uses-material-design: true
